name: CI/CD for my-frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1) 체크아웃
      - name: Check out code
        uses: actions/checkout@v2

      # 2) Docker 로그인
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 3) Docker 이미지 빌드 및 푸시
      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest
      
      - name: Trigger jenkins Deployment
        run: |
          curl -X POST "http://112.219.163.139:8080/job/biblo_frontend/build?token=111e7e952b6233a6fe96674f5e36e27ec8"
